spring:
  #Kafka config
  kafka:
    producer:
      bootstrap-servers: http://localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: task-service
      bootstrap-servers: http://localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    security:
      protocol: PLAINTEXT
    topics:
      user-saved-topic: user-saved
      task-created-topic: task-created
      task-updated-topic: task-updated
    properties:
      schema:
        registry:
          url: http://localhost:9898
      specific:
        avro:
          reader: true
    bootstrap-servers: http://localhost:9092
